SONARKT-291 Implement rule S6516: Functional interface implementations should use lambda expressions
SonarSource/sonar-kotlin pull request #289
Opened 2023-03-27 14:13 UTC by kaufco

2023-03-29 09:07 UTC, leveretka requested changes

2023-04-03 12:47 UTC, kaufco commented on sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/checks/SamConversionCheckTest.kt
> +    fun testFlexibleType() {
Fixed.

2023-04-03 12:49 UTC, kaufco commented on sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/checks/SamConversionCheck.kt
> +        val superType = superTypeEntry.typeReference?.getType(context.bindingContext) as? SimpleType ?: return
Fixed.

2023-04-03 12:50 UTC, kaufco commented on sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/api/ApiExtensions.kt
> +    //       KtObjectDeclaration (companion objects), but they are allowed inside function interfaces
Fixed.

2023-04-03 13:20 UTC, kaufco commented on sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/api/ApiExtensions.kt
> +    return getSingleAbstractMethodOrNull(constructor.declarationDescriptor as ClassDescriptor) != null
The function itself is general enough for the APIExtensions I think. A service function that returns whether a KotlinType is a functional interface might come in handy. 

The question is whether the implementation is general enough, too. I'm using `getAbstractSingleMethodOrNull` here, which comes from `org.jetbrains.kotlin.resolve.sam`, and it's assumption is that we have a `ClassDescriptor` available.

The case that `declarationConstructor` is either `null` or not a `ClassDescriptor` is now handled correctly and `false` is returned in that case. What still bothers me is: When can it be null? Probably when the type does not belong to the compilation source but comes from a JAR? Wdyt?

2023-04-03 15:18 UTC, leveretka approved these changes
Nice work on the rule, looks good!

2023-04-06 16:41 UTC, merged