SONARKT-100 Create rule S1128: Unnecessary imports should be removed
SonarSource/sonar-kotlin pull request #66
Opened 2021-08-17 10:11 UTC by johann-beleites-sonarsource

2021-08-19 10:26 UTC, margarita-nedzelska-sonarsource requested changes
Overall looks good, just a few points to revisit and improve

2021-08-19 10:26 UTC, margarita-nedzelska-sonarsource commented on sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/checks/UnnecessaryImportsCheck.kt
> +    private fun collectData(file: KtFile) =
How about?
```suggestion
    private fun collectReferences(file: KtFile) =
```

2021-08-19 10:26 UTC, margarita-nedzelska-sonarsource commented on sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/checks/UnnecessaryImportsCheck.kt
> +                relevantImports
The `return@` here signals it could be a separate function to improve the readability

2021-08-19 10:26 UTC, margarita-nedzelska-sonarsource commented on sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/checks/UnnecessaryImportsCheck.kt
> +        }.filterKeys { simpleName ->
I'd suggest putting small one-line lambdas on the same line with the function invocation. so we'll have sth like:
```
 file.importDirectives
     .filter { ... }
     .groupBy { ... }
     .filterKeys { ... }
 ```

  And big lambdas could on the next lines or even become an extracted private methods

2021-08-19 10:26 UTC, margarita-nedzelska-sonarsource commented on sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/checks/UnnecessaryImportsCheck.kt
> +import org.jetbrains.kotlin.fir.builder.toBinaryName
This import is coming from `fir` package. Are you sure we can rely on it?

2021-08-19 10:26 UTC, margarita-nedzelska-sonarsource commented on sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/checks/UnnecessaryImportsCheck.kt
> +        file.importDirectives.filter { imp ->
Maybe this whole pipeline could become a private function?

2021-08-19 10:26 UTC, margarita-nedzelska-sonarsource commented on sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/checks/UnnecessaryImportsCheck.kt
> +            getArrayAccessImportsFilter(arrayAccesses, bindingContext)
It's the matter of taste but looks like this lambda is small enough to be on the same line as `lazy`

2021-08-19 10:26 UTC, margarita-nedzelska-sonarsource commented on sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/checks/UnnecessaryImportsCheck.kt
> +                relevantTopLevelChildren.flattenNodes()
Do we need really to flattenNodes? It looks like you can use `KtTreeVisitorVoid` and visit children of elements

2021-08-19 10:26 UTC, margarita-nedzelska-sonarsource commented on sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/checks/UnnecessaryImportsCheck.kt
> +import org.jetbrains.kotlin.psi.psiUtil.isDotSelector
Looks like that import is unused

2021-09-01 14:59 UTC, johann-beleites-sonarsource commented on sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/checks/UnnecessaryImportsCheck.kt
> +import org.jetbrains.kotlin.psi.psiUtil.isDotSelector
How ironic

2021-09-06 11:23 UTC, margarita-nedzelska-sonarsource approved these changes

2021-09-06 11:24 UTC, merged